// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Types$Reasonml = require("./Types.bs.js");

function sendGreetings(email) {
  if (email.TAG) {
    if (email._0) {
      console.log("Invalid Email!");
    } else {
      console.log("Empty String!");
    }
    return ;
  }
  console.log("Hey, " + Types$Reasonml.Email.value(email._0));
  
}

var emailEmpty = Types$Reasonml.Email.create("");

var emailFail = Types$Reasonml.Email.create("lero");

var emailOk = Types$Reasonml.Email.create("lero@lero.com");

sendGreetings(emailEmpty);

sendGreetings(emailFail);

sendGreetings(emailOk);

exports.sendGreetings = sendGreetings;
exports.emailEmpty = emailEmpty;
exports.emailFail = emailFail;
exports.emailOk = emailOk;
/* emailEmpty Not a pure module */
