// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function create(str) {
  if (str === "") {
    return {
            TAG: /* Error */1,
            _0: /* EmptyString */0
          };
  } else if (str.includes("@")) {
    return {
            TAG: /* Ok */0,
            _0: str
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: /* InvalidEmail */1
          };
  }
}

function value(str) {
  return str;
}

var Email = {
  create: create,
  value: value
};

function sendGreetings(email) {
  if (email.TAG) {
    if (email._0) {
      console.log("Invalid Email!");
    } else {
      console.log("Empty String!");
    }
    return ;
  }
  console.log("Hey, " + email._0);
  
}

var emailEmpty = create("");

var emailFail = create("lero");

var emailOk = create("lero@lero.com");

sendGreetings(emailEmpty);

sendGreetings(emailFail);

sendGreetings(emailOk);

exports.Email = Email;
exports.sendGreetings = sendGreetings;
exports.emailEmpty = emailEmpty;
exports.emailFail = emailFail;
exports.emailOk = emailOk;
/* emailEmpty Not a pure module */
