// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function sendGreetings(employee) {
  return Promise.resolve((console.log("\n      Subject: Happy birthday!\n\n      Happy birthday, dear " + employee + ".email!\n    "), undefined));
}

exports.sendGreetings = sendGreetings;
/* No side effect */
